[build-system]
requires = ["uv_build>=0.12.17,<0.13"]
build-backend = "uv_build"

[project]
name = "textual_jsonschema_form"
version = "0.1.0"
description = "Textual forms based on jsonschema"
authors = [{ name = "Lukas Burkhard", email = "dev@lksch.ch" }]
requires-python = ">=3.12,<4.0"
dependencies = [
    "textual>=0.40.0",
]

[project.urls]
Repository = "https://github.com/gh-PonyM/textual-jsonschema-form"
Documentation = "https://gh-PonyM.github.io/textual-jsonschema-form/"

[dependency-groups]
dev = [
    "bump2version>=1.0.1",
    "pre-commit>=4.6.2",
    "pydantic>=2.13.5",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.8",
    "textual-dev>=1.8.0",
    "tox>=4.61.5",
    "tox-uv>=1.36.0",
    "ty>=0.0.82",
]
docs = [
    "mkdocs>=1.4.2",
    "mkdocs-material>=9.2.7",
    "mkdocstrings[python]>=0.23.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
pythonpath = ["."]

[tool.ruff]
target-version = "py312"
line-length = 88
fix = true

[tool.ruff.lint]
select = [
    "YTT",
    "S",
    "B",
    "A",
    "C4",
    "T10",
    "SIM",
    "I",
    "C90",
    "E", "W",
    "F",
    "PGH",
    "UP",
    "RUF",
    "TRY",
]
ignore = [
    "E501",
    "E731",
    "A002",
    "A003",
    "RUF012",
    "C408",
    "RUF015",
    "C901",
    "TRY003",
    "PGH003"
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["textual_jsonschema_form"]
